language: node_js
node_js:
  - node
sudo: required
cache:
  directories:
    - node_modules
env:
  global:
    - AWS_REGION=us-east-1
    - SLS_DEBUG=true
before_install:
    - npm install -g serverless
before_script: chmod 0777 ./deployment/deploy.sh
script: ./deployment/deploy.sh
