service: donation-app
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
functions:
  app:
    handler: app.handler
    package: public/
    events:
      - http:
          path: /
          method: get
      - http:
          path: /receiveDonation
          method: post
      - http:
          path: /data
          method: get
      - http:
          path: /js/app.js
          method: get
plugins:
  - serverless-offline
