service: donation-app
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
